SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE TABLE defects;
TRUNCATE TABLE test_execution_steps;
TRUNCATE TABLE test_executions;
TRUNCATE TABLE user_story_criterias;
TRUNCATE TABLE user_stories;
TRUNCATE TABLE test_cases;
TRUNCATE TABLE test_suites;
TRUNCATE TABLE test_plans;
TRUNCATE TABLE versions;
TRUNCATE TABLE users_projects;
TRUNCATE TABLE projects;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS = 1; 